-- EcoWallet Supabase Schema Setup
-- Run this in the Supabase SQL Editor

-- 1. TABLES

-- Public Users table (Syncs with auth.users)
drop table if exists public.users cascade;
create table public.users (
  id uuid references auth.users not null primary key,
  email text,
  name text,
  state text,
  role text default 'user' check (role in ('user', 'agent', 'admin')),
  deleted_at timestamp with time zone,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Wallets table
drop table if exists public.wallets cascade;
create table public.wallets (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null unique,
  balance decimal(15, 2) default 0.00 check (balance >= 0),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Waste Submissions table
drop table if exists public.waste_submissions cascade;
create table public.waste_submissions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  agent_id uuid references public.users(id) on delete set null,
  material_type text not null,
  weight_kg decimal(10, 3) not null,
  location text,
  payout decimal(15, 2) default 0,
  co2_saved decimal(10, 3) default 0,
  status text default 'pending' check (status in ('pending', 'collected', 'rejected')),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- Withdrawal Requests table
drop table if exists public.withdrawal_requests cascade;
create table public.withdrawal_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id) on delete cascade not null,
  amount decimal(15, 2) not null check (amount > 0),
  method text not null,
  phone_number text,
  bank_details jsonb,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

-- 2. VIEWS (For Dashboards)

create or replace view public.user_stats as
select 
    u.id,
    u.name,
    u.email,
    count(ws.id) as total_submissions,
    coalesce(sum(ws.weight_kg), 0) as total_weight_kg,
    coalesce(sum(ws.co2_saved), 0) as total_co2_saved,
    coalesce(w.balance, 0) as wallet_balance
from public.users u
left join public.waste_submissions ws on u.id = ws.user_id
left join public.wallets w on u.id = w.user_id
group by u.id, u.name, u.email, w.balance;

create or replace view public.leaderboard as
select 
    u.id,
    u.name,
    coalesce(sum(ws.weight_kg), 0) as total_waste_kg,
    coalesce(sum(ws.co2_saved), 0) as total_co2_saved
from public.users u
left join public.waste_submissions ws on u.id = ws.user_id and ws.status = 'collected'
where u.role = 'user'
group by u.id, u.name
order by total_waste_kg desc;

create or replace view public.platform_stats as
select 
    (select count(*) from public.users where role = 'user') as total_users,
    (select count(*) from public.users where role = 'agent') as total_agents,
    (select count(*) from public.users where role = 'admin') as total_admins,
    coalesce((select sum(weight_kg) from public.waste_submissions where status = 'collected'), 0) as total_waste_recycled_kg,
    coalesce((select sum(co2_saved) from public.waste_submissions where status = 'collected'), 0) as total_co2_saved_kg,
    coalesce((select sum(payout) from public.waste_submissions where status = 'collected'), 0) as total_payouts,
    (select count(*) from public.waste_submissions where status = 'pending') as pending_submissions,
    (select count(*) from public.withdrawal_requests where status = 'pending') as pending_withdrawals;

-- 3. FUNCTIONS & TRIGGERS

-- Handle New User (Sync Auth -> Public & Create Wallet)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (id, email, name, role, state)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'name',
    coalesce(new.raw_user_meta_data->>'role', 'user'),
    new.raw_user_meta_data->>'state'
  );
  insert into public.wallets (user_id, balance) values (new.id, 0);
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Calculate Rewards (Price & CO2)
create or replace function calculate_waste_rewards()
returns trigger as $$
begin
  -- Prices: PET:450, HDPE:420, Aluminum:1200, Paper:150
  if new.material_type = 'PET' then new.payout := new.weight_kg * 450; new.co2_saved := new.weight_kg * 1.5;
  elsif new.material_type = 'HDPE' then new.payout := new.weight_kg * 420; new.co2_saved := new.weight_kg * 1.8;
  elsif new.material_type = 'Aluminum' then new.payout := new.weight_kg * 1200; new.co2_saved := new.weight_kg * 9.0;
  elsif new.material_type = 'Paper' then new.payout := new.weight_kg * 150; new.co2_saved := new.weight_kg * 0.8;
  else new.payout := 0; new.co2_saved := 0;
  end if;
  return new;
end;
$$ language plpgsql;

drop trigger if exists before_waste_insert on public.waste_submissions;
create trigger before_waste_insert
  before insert on public.waste_submissions
  for each row execute function calculate_waste_rewards();

-- Update Wallet on Collection
drop function if exists update_wallet_on_submission();
drop trigger if exists after_waste_insert_wallet on public.waste_submissions;
drop trigger if exists after_waste_collected_wallet on public.waste_submissions;

create or replace function update_wallet_on_collection()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Credit wallet only when status changes to collected
  if new.status = 'collected' and coalesce(old.status, '') <> 'collected' then
    update public.wallets
      set balance = balance + coalesce(new.payout, 0)
      where user_id = new.user_id;
  end if;
  return new;
end;
$$;

create trigger after_waste_collected_wallet
  after update on public.waste_submissions
  for each row execute function update_wallet_on_collection();

-- RPC: Get Agent Stats
drop function if exists get_agent_stats();
create or replace function get_agent_stats()
returns json
language plpgsql security definer
as $$
declare
  v_agent_id uuid;
  result json;
begin
  v_agent_id := auth.uid();
  select json_build_object(
    'total_collections', count(*),
    'total_weight_kg', coalesce(sum(weight_kg), 0),
    'total_co2_saved', coalesce(sum(co2_saved), 0)
  ) into result
  from public.waste_submissions
  where agent_id = v_agent_id and status = 'collected';
  return result;
end;
$$;

-- 4. ROW LEVEL SECURITY (RLS)

alter table public.users enable row level security;
alter table public.wallets enable row level security;
alter table public.waste_submissions enable row level security;
alter table public.withdrawal_requests enable row level security;

-- Policies

-- Users
drop policy if exists "Public read access" on public.users;
create policy "Public read access" on public.users for select using (true);
drop policy if exists "User update own" on public.users;
create policy "User update own" on public.users for update using (auth.uid() = id);

-- Wallets
drop policy if exists "View own wallet" on public.wallets;
create policy "View own wallet" on public.wallets for select using (auth.uid() = user_id);

-- Waste Submissions
drop policy if exists "View own submissions" on public.waste_submissions;
create policy "View own submissions" on public.waste_submissions for select using (auth.uid() = user_id);
drop policy if exists "Agent view all" on public.waste_submissions;
create policy "Agent view all" on public.waste_submissions for select using (
  exists (select 1 from public.users where id = auth.uid() and role in ('agent', 'admin'))
);
drop policy if exists "User insert own" on public.waste_submissions;
create policy "User insert own" on public.waste_submissions for insert with check (auth.uid() = user_id);
drop policy if exists "Agent update" on public.waste_submissions;
create policy "Agent update" on public.waste_submissions for update using (
  exists (select 1 from public.users where id = auth.uid() and role in ('agent', 'admin'))
);

-- Withdrawal Requests
drop policy if exists "View own withdrawals" on public.withdrawal_requests;
create policy "View own withdrawals" on public.withdrawal_requests for select using (auth.uid() = user_id);
drop policy if exists "Admin view all withdrawals" on public.withdrawal_requests;
create policy "Admin view all withdrawals" on public.withdrawal_requests for select using (
  exists (select 1 from public.users where id = auth.uid() and role = 'admin')
);
drop policy if exists "User insert withdrawal" on public.withdrawal_requests;
create policy "User insert withdrawal" on public.withdrawal_requests for insert with check (auth.uid() = user_id);
drop policy if exists "Admin update withdrawal" on public.withdrawal_requests;
create policy "Admin update withdrawal" on public.withdrawal_requests for update using (
  exists (select 1 from public.users where id = auth.uid() and role = 'admin')
);
